---
title: "Package development with furrr"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

When developing a package that imports and calls functions from furrr, you'll likely be using `devtools::load_all()` as part of your development process. It is likely that unless you install your package, you might run into issues where functions internal to your package aren't being exported to your workers (see [issue #95](https://github.com/DavisVaughan/furrr/issues/95)).

Specifically, if you do the following, you will probably have issues:

1) Your package has not yet been _installed_ on your machine, or you have an old version installed.

2) You call `devtools::load_all()`.

3) You set up a multisession or multicore strategy for furrr.

4) You call `future_map()` or any other furrr function from inside your package, and `.f` contains a function specific to your package.

In this example, the underlying globals package will likely think that the function you called from `.f` is part of a package that is installed on your machine, so it won't try and export it to the workers. Instead, it will just try and load up that package on the worker to get access to the function. Since the package hasn't been installed on your machine yet (`load_all()` just _mocks_ a fake installation) the workers will fail to attach it.

The solution is just to install your package with `devtools::install()` or using the RStudio Build pane, and then to restart R. Make sure that you re-install whenever you make any additional changes to the package.
